In [70]:
# Greenblatt's Magic Formula Implementation

import requests
from bs4 import BeautifulSoup
import pandas as pd

In [71]:
tickers = ["MMM","AXP","AAPL","BA","CAT","CVX","CSCO","KO","DIS","DWDP",
           "XOM","GE","GS","HD","IBM","INTC","JNJ","JPM","MCD","MRK",
           "MSFT","NKE","PFE","PG","TRV","UTX","UNH","VZ","V","WMT"]

In [72]:
#list of tickers whose financial data needs to be extracted
financial_dir = {}

In [130]:
for ticker in tickers:
    try:
    #getting balance sheet data from yahoo finance for the given ticker
        temp_dir = {}
        url = 'https://in.finance.yahoo.com/quote/'+ticker+'/balance-sheet?p='+ticker
        page = requests.get(url)
        page_content = page.content
        soup = BeautifulSoup(page_content,'html.parser')
        tabl = soup.find_all("div", {"class" : "M(0) Whs(n) BdEnd Bdc($seperatorColor) D(itb)"})
        for t in tabl:
            rows = t.find_all("div", {"class" : "rw-expnded"})
            for row in rows:
                temp_dir[row.get_text(separator='|').split("|")[0]]=row.get_text(separator='|').split("|")[1]
        
        #getting income statement data from yahoo finance for the given ticker
        url = 'https://in.finance.yahoo.com/quote/'+ticker+'/financials?p='+ticker
        page = requests.get(url)
        page_content = page.content
        soup = BeautifulSoup(page_content,'html.parser')
        tabl = soup.find_all("div", {"class" : "M(0) Whs(n) BdEnd Bdc($seperatorColor) D(itb)"})
        for t in tabl:
            rows = t.find_all("div", {"class" : "rw-expnded"})
            for row in rows:
                temp_dir[row.get_text(separator='|').split("|")[0]]=row.get_text(separator='|').split("|")[1]
        
        #getting cashflow statement data from yahoo finance for the given ticker
        url = 'https://in.finance.yahoo.com/quote/'+ticker+'/cash-flow?p='+ticker
        page = requests.get(url)
        page_content = page.content
        soup = BeautifulSoup(page_content,'html.parser')
        tabl = soup.find_all("div", {"class" : "M(0) Whs(n) BdEnd Bdc($seperatorColor) D(itb)"})
        for t in tabl:
            rows = t.find_all("div", {"class" : "rw-expnded"})
            for row in rows:
                temp_dir[row.get_text(separator='|').split("|")[0]]=row.get_text(separator='|').split("|")[1]
        
        #getting key statistics data from yahoo finance for the given ticker
        url = 'https://in.finance.yahoo.com/quote/'+ticker+'/key-statistics?p='+ticker
        page = requests.get(url)
        page_content = page.content
        soup = BeautifulSoup(page_content,'html.parser')
        tabl = soup.findAll("table", {"class": "W(100%) Bdcl(c) "}) # try soup.findAll("table") if this line gives error 
        for t in tabl:
            rows = t.find_all("tr")
            for row in rows:
                if len(row.get_text(separator='|').split("|")[0:2])>0:
                    temp_dir[row.get_text(separator='|').split("|")[0]]=row.get_text(separator='|').split("|")[-1]    
        
        #combining all extracted information with the corresponding ticker
        financial_dir[ticker] = temp_dir
    except:
        print("Problem scraping data for ",ticker)

In [131]:
financial_dir["MSFT"] # Let's check out one of the stocks

{'Assets': 'Current assets',
 'Current assets': 'Cash',
 'Cash': 'Cash and cash equivalents',
 'Cash and cash equivalents': '1,35,76,000',
 'Other short-term investments': '12,29,51,000',
 'Total cash': '13,65,27,000',
 'Net receivables': '3,20,11,000',
 'Inventory': '-6,00,000',
 'Other current assets': '1,14,82,000',
 'Total current assets': '18,19,15,000',
 'Non-current assets': 'Property, plant and equipment',
 'Property, plant and equipment': 'Gross property, plant and equipment',
 'Gross property, plant and equipment': '9,61,01,000',
 'Accumulated depreciation': '-4,31,97,000',
 'Net property, plant and equipment': '5,29,04,000',
 'Equity and other investments': '29,65,000',
 'Goodwill': '4,33,51,000',
 'Intangible assets': '70,38,000',
 'Other long-term assets': '1,31,38,000',
 'Total non-current assets': '11,93,96,000',
 'Total assets': '30,13,11,000',
 "Liabilities and stockholders' equity": 'Liabilities',
 'Liabilities': 'Current liabilities',
 'Current liabilities': 'Current debt',
 'Current debt': '37,49,000',
 'Accounts payable': '42,07,000',
 'Taxes payable': '21,30,000',
 'Deferred revenues': '31,80,000',
 'Other current liabilities': '1,00,27,000',
 'Total current liabilities': '7,23,10,000',
 'Non-current liabilities': 'Long-term debt',
 'Long-term debt': '5,95,78,000',
 'Deferred tax liabilities': '2,04,000',
 'Other long-term liabilities': '1,06,32,000',
 'Total non-current liabilities': '11,06,97,000',
 'Total liabilities': '18,30,07,000',
 "Stockholders' equity": 'Common stock',
 'Common stock': '8,05,52,000',
 'Retained earnings': '3,45,66,000',
 'Accumulated other comprehensive income': '31,86,000',
 "Total stockholders' equity": '11,83,04,000',
 "Total liabilities and stockholders' equity": '30,13,11,000',
 'Total revenue': '15,99,69,000',
 'Cost of revenue': '5,05,80,000',
 'Gross profit': '10,93,89,000',
 'Operating expenses': 'Research development',
 'Research development': '2,02,43,000',
 'Selling general and administrative': '2,49,18,000',
 'Total operating expenses': '4,51,61,000',
 'Operating income or loss': '6,42,28,000',
 'Interest expense': '24,79,000',
 'Total other income/expenses net': '38,21,000',
 'Income before tax': '6,51,19,000',
 'Income tax expense': '91,04,000',
 'Income from continuing operations': '5,60,15,000',
 'Net income': '5,60,15,000',
 'Net income available to common shareholders': '5,60,15,000',
 'Basic EPS': '-',
 'Diluted EPS': '-',
 'Basic average shares': '-',
 'Diluted average shares': '-',
 'EBITDA': '-',
 'Cash flows from operating activities': 'Net income',
 'Depreciation & amortisation': '1,18,46,000',
 'Deferred income taxes': '-33,00,000',
 'Stock-based compensation': '58,96,000',
 'Change in working capital': '31,58,000',
 'Accounts receivable': '-42,30,000',
 'Other working capital': '5,37,89,000',
 'Net cash provided by operating activities': '7,27,03,000',
 'Cash flows from investing activities ': 'Investments in property, plant and equipment',
 'Investments in property, plant and equipment': '-1,89,14,000',
 'Acquisitions, net': '-1,00,58,000',
 'Purchases of investments': '-6,69,26,000',
 'Sales/maturities of investments': '7,73,09,000',
 'Other investing activities': '-',
 'Net cash used for investing activities': '-2,11,86,000',
 'Cash flows from financing activities': 'Debt repayment',
 'Debt repayment': '-37,50,000',
 'Common stock issued': '15,83,000',
 'Common stock repurchased': '-2,59,99,000',
 'Dividends paid': '-1,61,72,000',
 'Other financing activities': '-50,39,000',
 'Net cash used provided by (used for) financing activities': '-4,93,77,000',
 'Net change in cash': '19,92,000',
 'Cash at beginning of period': '1,17,10,000',
 'Cash at end of period': '1,38,50,000',
 'Free cash flow': '5,37,89,000',
 'Operating cash flow': '7,27,03,000',
 'Capital expenditure': '-1,89,14,000'}

In [154]:
#storing information in pandas dataframe
combined_financials = pd.DataFrame(financial_dir)
combined_financials

,MMM,AXP,AAPL,BA,CAT,CVX,CSCO,KO,DIS,XOM,...,MRK,MSFT,NKE,PFE,PG,TRV,UNH,VZ,V,WMT
Assets,Current assets,Total assets,Current assets,Current assets,Current assets,Current assets,Current assets,Current assets,Current assets,Current assets,...,Current assets,Current assets,Current assets,Current assets,Current assets,Total assets,Current assets,Current assets,Current assets,Current assets
Current assets,Cash,NaN,Cash,Cash,Cash,Cash,Cash,Cash,Cash,Cash,...,Cash,Cash,Cash,Cash,Cash,NaN,Cash,Cash,Cash,Cash
Cash,Cash and cash equivalents,NaN,Cash and cash equivalents,Cash and cash equivalents,Total cash,Cash and cash equivalents,Cash and cash equivalents,Cash and cash equivalents,Cash and cash equivalents,Cash and cash equivalents,...,Cash and cash equivalents,Cash and cash equivalents,Cash and cash equivalents,Cash and cash equivalents,Cash and cash equivalents,NaN,Cash and cash equivalents,Cash and cash equivalents,Cash and cash equivalents,Cash and cash equivalents
Cash and cash equivalents,"46,34,000",NaN,"3,80,16,000","77,52,000",NaN,"55,96,000","1,18,09,000","67,95,000","1,79,14,000","43,64,000",...,"80,62,000","1,35,76,000","83,48,000","17,84,000","1,61,81,000",NaN,"1,69,21,000","2,21,71,000","1,62,89,000","1,77,41,000"
Other short-term investments,"4,04,000",NaN,"5,29,27,000","1,78,38,000",NaN,"31,000","1,76,10,000","41,19,000",NaN,NaN,...,0,"12,29,51,000","4,39,000","1,04,37,000",0,NaN,"28,60,000",NaN,"37,52,000",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Cash at beginning of period,"42,53,000","3,86,08,000","4,30,49,000","1,50,39,000","71,30,000","96,90,000","84,99,000","1,39,65,000","68,74,000",-,...,"74,60,000","1,17,10,000","28,63,000",-,"1,53,93,000","5,44,000","2,15,69,000","83,24,000","1,28,16,000","95,15,000"
Cash at end of period,"46,08,000","3,99,88,000","4,00,06,000","69,48,000","1,12,96,000",-,"1,18,03,000","86,99,000","1,69,76,000",-,...,"68,04,000","1,38,50,000","84,39,000",-,"99,02,000","6,32,000","1,99,93,000","1,14,95,000","1,91,90,000","1,77,88,000"
Free cash flow,"71,09,000","86,28,000","9,04,73,000","-1,86,61,000","50,54,000","25,66,000","1,43,72,000","98,58,000","26,47,000",-,...,"65,05,000","5,37,89,000","38,34,000",-,"1,63,25,000","70,81,000","2,30,86,000","-2,12,49,000","1,12,93,000","2,58,10,000"
Operating cash flow,"85,88,000","1,00,90,000","9,95,91,000","-1,74,95,000","71,25,000","1,00,55,000","1,51,09,000","1,09,24,000","60,91,000",-,...,"1,13,37,000","7,27,03,000","46,44,000",-,"1,90,56,000","70,81,000","2,52,36,000","4,26,38,000","1,19,40,000","3,60,74,000"
Capital expenditure,"-14,79,000","-14,62,000","-91,18,000","-11,66,000","-20,71,000","-74,89,000","-7,37,000","-10,66,000","-34,44,000",-,...,"-48,32,000","-1,89,14,000","-8,10,000",-,"-27,31,000",NaN,"-21,50,000","-6,38,87,000","-6,47,000","-1,02,64,000"

In [155]:
combined_financials.dropna(how='all',axis=1,inplace=True) #dropping columns with all NaN values
combined_financials

,MMM,AXP,AAPL,BA,CAT,CVX,CSCO,KO,DIS,XOM,...,MRK,MSFT,NKE,PFE,PG,TRV,UNH,VZ,V,WMT
Assets,Current assets,Total assets,Current assets,Current assets,Current assets,Current assets,Current assets,Current assets,Current assets,Current assets,...,Current assets,Current assets,Current assets,Current assets,Current assets,Total assets,Current assets,Current assets,Current assets,Current assets
Current assets,Cash,NaN,Cash,Cash,Cash,Cash,Cash,Cash,Cash,Cash,...,Cash,Cash,Cash,Cash,Cash,NaN,Cash,Cash,Cash,Cash
Cash,Cash and cash equivalents,NaN,Cash and cash equivalents,Cash and cash equivalents,Total cash,Cash and cash equivalents,Cash and cash equivalents,Cash and cash equivalents,Cash and cash equivalents,Cash and cash equivalents,...,Cash and cash equivalents,Cash and cash equivalents,Cash and cash equivalents,Cash and cash equivalents,Cash and cash equivalents,NaN,Cash and cash equivalents,Cash and cash equivalents,Cash and cash equivalents,Cash and cash equivalents
Cash and cash equivalents,"46,34,000",NaN,"3,80,16,000","77,52,000",NaN,"55,96,000","1,18,09,000","67,95,000","1,79,14,000","43,64,000",...,"80,62,000","1,35,76,000","83,48,000","17,84,000","1,61,81,000",NaN,"1,69,21,000","2,21,71,000","1,62,89,000","1,77,41,000"
Other short-term investments,"4,04,000",NaN,"5,29,27,000","1,78,38,000",NaN,"31,000","1,76,10,000","41,19,000",NaN,NaN,...,0,"12,29,51,000","4,39,000","1,04,37,000",0,NaN,"28,60,000",NaN,"37,52,000",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Cash at beginning of period,"42,53,000","3,86,08,000","4,30,49,000","1,50,39,000","71,30,000","96,90,000","84,99,000","1,39,65,000","68,74,000",-,...,"74,60,000","1,17,10,000","28,63,000",-,"1,53,93,000","5,44,000","2,15,69,000","83,24,000","1,28,16,000","95,15,000"
Cash at end of period,"46,08,000","3,99,88,000","4,00,06,000","69,48,000","1,12,96,000",-,"1,18,03,000","86,99,000","1,69,76,000",-,...,"68,04,000","1,38,50,000","84,39,000",-,"99,02,000","6,32,000","1,99,93,000","1,14,95,000","1,91,90,000","1,77,88,000"
Free cash flow,"71,09,000","86,28,000","9,04,73,000","-1,86,61,000","50,54,000","25,66,000","1,43,72,000","98,58,000","26,47,000",-,...,"65,05,000","5,37,89,000","38,34,000",-,"1,63,25,000","70,81,000","2,30,86,000","-2,12,49,000","1,12,93,000","2,58,10,000"
Operating cash flow,"85,88,000","1,00,90,000","9,95,91,000","-1,74,95,000","71,25,000","1,00,55,000","1,51,09,000","1,09,24,000","60,91,000",-,...,"1,13,37,000","7,27,03,000","46,44,000",-,"1,90,56,000","70,81,000","2,52,36,000","4,26,38,000","1,19,40,000","3,60,74,000"
Capital expenditure,"-14,79,000","-14,62,000","-91,18,000","-11,66,000","-20,71,000","-74,89,000","-7,37,000","-10,66,000","-34,44,000",-,...,"-48,32,000","-1,89,14,000","-8,10,000",-,"-27,31,000",NaN,"-21,50,000","-6,38,87,000","-6,47,000","-1,02,64,000"

In [156]:
# Updating the tickers list based on only those tickers whose values were successfully extracted
tickers = combined_financials.columns 
tickers

Index(['MMM', 'AXP', 'AAPL', 'BA', 'CAT', 'CVX', 'CSCO', 'KO', 'DIS', 'XOM',
       'GE', 'GS', 'HD', 'IBM', 'INTC', 'JNJ', 'JPM', 'MCD', 'MRK', 'MSFT',
       'NKE', 'PFE', 'PG', 'TRV', 'UNH', 'VZ', 'V', 'WMT'],
      dtype='object')

In [157]:
cf_index =combined_financials.index
cf_index

Index(['Assets', 'Current assets', 'Cash', 'Cash and cash equivalents',
       'Other short-term investments', 'Total cash', 'Net receivables',
       'Inventory', 'Other current assets', 'Total current assets',
       'Non-current assets', 'Property, plant and equipment',
       'Gross property, plant and equipment', 'Accumulated depreciation',
       'Net property, plant and equipment', 'Equity and other investments',
       'Goodwill', 'Intangible assets', 'Other long-term assets',
       'Total non-current assets', 'Total assets',
       'Liabilities and stockholders' equity', 'Liabilities',
       'Current liabilities', 'Current debt', 'Accounts payable',
       'Taxes payable', 'Accrued liabilities', 'Deferred revenues',
       'Other current liabilities', 'Total current liabilities',
       'Non-current liabilities', 'Long-term debt', 'Deferred tax liabilities',
       'Other long-term liabilities', 'Total non-current liabilities',
       'Total liabilities', 'Stockholders' equity', 'Common stock',
       'Retained earnings', 'Accumulated other comprehensive income',
       'Total stockholders' equity',
       'Total liabilities and stockholders' equity', 'Total revenue',
       'Cost of revenue', 'Gross profit', 'Operating expenses',
       'Research development', 'Selling general and administrative',
       'Total operating expenses', 'Operating income or loss',
       'Interest expense', 'Total other income/expenses net',
       'Income before tax', 'Income tax expense',
       'Income from continuing operations', 'Net income',
       'Net income available to common shareholders', 'Basic EPS',
       'Diluted EPS', 'Basic average shares', 'Diluted average shares',
       'EBITDA', 'Cash flows from operating activities',
       'Depreciation & amortisation', 'Deferred income taxes',
       'Stock-based compensation', 'Change in working capital',
       'Accounts receivable', 'Other working capital', 'Other non-cash items',
       'Net cash provided by operating activities',
       'Cash flows from investing activities ',
       'Investments in property, plant and equipment', 'Acquisitions, net',
       'Purchases of investments', 'Sales/maturities of investments',
       'Other investing activities', 'Net cash used for investing activities',
       'Cash flows from financing activities', 'Debt repayment',
       'Common stock issued', 'Common stock repurchased', 'Dividends paid',
       'Other financing activities',
       'Net cash used provided by (used for) financing activities',
       'Net change in cash', 'Cash at beginning of period',
       'Cash at end of period', 'Free cash flow', 'Operating cash flow',
       'Capital expenditure'],
      dtype='object')

In [159]:
# Series.str.contains() function to find if a pattern is contained in the string present in the underlying data of the given series object.

# Creating the Series
sr = pd.Series(['New_York', 'Lisbon', 56, 'Paris', 'Munich'])
  
# Creating the index
idx = ['City 1', 'City 2', 'City 3', 'City 4', 'City 5']

# set the index
sr.index = idx
  
# Print the series
print(sr)

# find if a pattern is contained in the string 
result = sr.str.contains(pat = '[a-z]')
  
# print the result
print(result)

City 1    New_York
City 2      Lisbon
City 3          56
City 4       Paris
City 5      Munich
dtype: object
City 1    True
City 2    True
City 3     NaN
City 4    True
City 5    True
dtype: object

In [160]:
combined_financials[ticker].str.contains("[a-z]")

Assets                           True
Current assets                   True
Cash                             True
Cash and cash equivalents       False
Other short-term investments      NaN
                                ...
Cash at beginning of period     False
Cash at end of period           False
Free cash flow                  False
Operating cash flow             False
Capital expenditure             False
Name: WMT, Length: 92, dtype: object

In [161]:
combined_financials[ticker].str.contains("[a-z]").fillna(False)

Assets                           True
Current assets                   True
Cash                             True
Cash and cash equivalents       False
Other short-term investments    False
                                ...
Cash at beginning of period     False
Cash at end of period           False
Free cash flow                  False
Operating cash flow             False
Capital expenditure             False
Name: WMT, Length: 92, dtype: bool

In [168]:
for ticker in tickers:
    combined_financials = combined_financials[~combined_financials[ticker].str.contains("[a-z]").fillna(False)]
    
combined_financials

,MMM,AXP,AAPL,BA,CAT,CVX,CSCO,KO,DIS,XOM,...,MRK,MSFT,NKE,PFE,PG,TRV,UNH,VZ,V,WMT
Cash and cash equivalents,"46,34,000",NaN,"3,80,16,000","77,52,000",NaN,"55,96,000","1,18,09,000","67,95,000","1,79,14,000","43,64,000",...,"80,62,000","1,35,76,000","83,48,000","17,84,000","1,61,81,000",NaN,"1,69,21,000","2,21,71,000","1,62,89,000","1,77,41,000"
Other short-term investments,"4,04,000",NaN,"5,29,27,000","1,78,38,000",NaN,"31,000","1,76,10,000","41,19,000",NaN,NaN,...,0,"12,29,51,000","4,39,000","1,04,37,000",0,NaN,"28,60,000",NaN,"37,52,000",NaN
Total cash,"50,38,000",NaN,"9,09,43,000","2,55,90,000","93,52,000","56,27,000","2,94,19,000","1,09,14,000","1,79,14,000","43,64,000",...,"80,62,000","13,65,27,000","87,87,000","1,22,21,000","1,61,81,000",NaN,"1,97,81,000","2,21,71,000","2,00,41,000","1,77,41,000"
Net receivables,"47,05,000",NaN,"1,61,20,000","23,85,000","1,67,80,000","1,14,71,000","54,72,000","31,44,000","1,12,99,000","1,63,39,000",...,"78,51,000","3,20,11,000","27,49,000","79,30,000","41,78,000",NaN,"1,28,70,000","2,39,17,000","16,18,000","65,16,000"
Inventory,"-1,88,000",NaN,"-20,52,000","-87,09,000","-1,50,000",-,"-86,000",-,"27,000",-,...,-,"-6,00,000","-7,25,000",-,"-5,03,000",NaN,NaN,-,NaN,"-23,95,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Cash at beginning of period,"42,53,000","3,86,08,000","4,30,49,000","1,50,39,000","71,30,000","96,90,000","84,99,000","1,39,65,000","68,74,000",-,...,"74,60,000","1,17,10,000","28,63,000",-,"1,53,93,000","5,44,000","2,15,69,000","83,24,000","1,28,16,000","95,15,000"
Cash at end of period,"46,08,000","3,99,88,000","4,00,06,000","69,48,000","1,12,96,000",-,"1,18,03,000","86,99,000","1,69,76,000",-,...,"68,04,000","1,38,50,000","84,39,000",-,"99,02,000","6,32,000","1,99,93,000","1,14,95,000","1,91,90,000","1,77,88,000"
Free cash flow,"71,09,000","86,28,000","9,04,73,000","-1,86,61,000","50,54,000","25,66,000","1,43,72,000","98,58,000","26,47,000",-,...,"65,05,000","5,37,89,000","38,34,000",-,"1,63,25,000","70,81,000","2,30,86,000","-2,12,49,000","1,12,93,000","2,58,10,000"
Operating cash flow,"85,88,000","1,00,90,000","9,95,91,000","-1,74,95,000","71,25,000","1,00,55,000","1,51,09,000","1,09,24,000","60,91,000",-,...,"1,13,37,000","7,27,03,000","46,44,000",-,"1,90,56,000","70,81,000","2,52,36,000","4,26,38,000","1,19,40,000","3,60,74,000"
Capital expenditure,"-14,79,000","-14,62,000","-91,18,000","-11,66,000","-20,71,000","-74,89,000","-7,37,000","-10,66,000","-34,44,000",-,...,"-48,32,000","-1,89,14,000","-8,10,000",-,"-27,31,000",NaN,"-21,50,000","-6,38,87,000","-6,47,000","-1,02,64,000"

In [225]:
combined_financials.index

Index(['Cash and cash equivalents', 'Other short-term investments',
       'Total cash', 'Net receivables', 'Inventory', 'Other current assets',
       'Total current assets', 'Gross property, plant and equipment',
       'Accumulated depreciation', 'Net property, plant and equipment',
       'Equity and other investments', 'Goodwill', 'Intangible assets',
       'Other long-term assets', 'Total non-current assets', 'Total assets',
       'Current debt', 'Accounts payable', 'Taxes payable',
       'Accrued liabilities', 'Deferred revenues', 'Other current liabilities',
       'Total current liabilities', 'Long-term debt',
       'Deferred tax liabilities', 'Other long-term liabilities',
       'Total non-current liabilities', 'Total liabilities', 'Common stock',
       'Retained earnings', 'Accumulated other comprehensive income',
       'Total stockholders' equity',
       'Total liabilities and stockholders' equity', 'Total revenue',
       'Cost of revenue', 'Gross profit', 'Research development',
       'Selling general and administrative', 'Total operating expenses',
       'Operating income or loss', 'Interest expense',
       'Total other income/expenses net', 'Income before tax',
       'Income tax expense', 'Income from continuing operations', 'Net income',
       'Net income available to common shareholders', 'Basic EPS',
       'Diluted EPS', 'Basic average shares', 'Diluted average shares',
       'EBITDA', 'Depreciation & amortisation', 'Deferred income taxes',
       'Stock-based compensation', 'Change in working capital',
       'Accounts receivable', 'Other working capital', 'Other non-cash items',
       'Net cash provided by operating activities',
       'Investments in property, plant and equipment', 'Acquisitions, net',
       'Purchases of investments', 'Sales/maturities of investments',
       'Other investing activities', 'Net cash used for investing activities',
       'Debt repayment', 'Common stock issued', 'Common stock repurchased',
       'Dividends paid', 'Other financing activities',
       'Net cash used provided by (used for) financing activities',
       'Net change in cash', 'Cash at beginning of period',
       'Cash at end of period', 'Free cash flow', 'Operating cash flow',
       'Capital expenditure'],
      dtype='object')

In [231]:
# creating dataframe with relevant financial information for each stock using fundamental data
stats = ["EBITDA",
         "Depreciation & amortisation", 
         "Net income available to common shareholders",
         "Net cash provided by operating activities",
         "Capital expenditure",
         "Total current assets",
         "Total current liabilities",
         "Investments in property, plant and equipment",
         "Total stockholders' equity",
         "Long-term debt"]

indx = ["EBITDA", "D&A", "NetIncome","CashFlowOps","Capex","CurrAsset","CurrLiab", "PPE", "BookValue", "TotDebt"]

In [232]:
all_stats = {}
for ticker in tickers:
    try:
        temp = combined_financials[ticker]
        ticker_stats = []
        for stat in stats:
            ticker_stats.append(temp.loc[stat])
        all_stats['{}'.format(ticker)] = ticker_stats
    except:
        print("can't read data for ",ticker)

In [233]:
all_stats

{'MMM': ['-',
  '19,31,000',
  '57,00,000',
  '85,88,000',
  '-14,79,000',
  '1,49,82,000',
  '79,48,000',
  '-14,79,000',
  '1,28,67,000',
  '1,79,89,000'],
 'AXP': [nan,
  '16,28,000',
  '49,09,000',
  '1,00,90,000',
  '-14,62,000',
  nan,
  nan,
  '-14,62,000',
  '2,29,84,000',
  nan],
 'AAPL': ['-',
  '1,09,17,000',
  '7,63,11,000',
  '9,95,91,000',
  '-91,18,000',
  '14,37,13,000',
  '10,53,92,000',
  '-91,18,000',
  '6,53,39,000',
  '9,86,67,000'],
 'BA': ['-',
  '22,26,000',
  '-1,17,82,000',
  '-1,74,95,000',
  '-11,66,000',
  '12,16,42,000',
  '8,72,80,000',
  '-11,66,000',
  '-1,83,16,000',
  '6,17,52,000'],
 'CAT': ['-',
  '24,04,000',
  '34,36,000',
  '71,25,000',
  '-20,71,000',
  '3,94,64,000',
  '2,57,17,000',
  '-20,71,000',
  '1,53,31,000',
  '2,58,96,000'],
 'CVX': ['-',
  nan,
  '-77,65,000',
  '1,00,55,000',
  '-74,89,000',
  '2,60,78,000',
  '2,21,83,000',
  '-74,89,000',
  '13,16,88,000',
  '4,23,20,000'],
 'CSCO': ['-',
  '17,77,000',
  '1,01,29,000',
  '1,51,09,000',
  '-7,37,000',
  '4,35,73,000',
  '2,53,31,000',
  '-7,37,000',
  '3,79,20,000',
  '1,15,78,000'],
 'KO': ['-',
  '15,35,000',
  '72,17,000',
  '1,09,24,000',
  '-10,66,000',
  '1,92,40,000',
  '1,46,01,000',
  '-10,66,000',
  '1,92,99,000',
  '4,01,25,000'],
 'DIS': ['-',
  '53,44,000',
  '-49,54,000',
  '60,91,000',
  '-34,44,000',
  '3,52,51,000',
  '2,66,28,000',
  '-34,44,000',
  '8,35,83,000',
  '5,29,17,000'],
 'XOM': ['-',
  '-',
  '-1,91,00,000',
  '-',
  '-',
  '4,48,93,000',
  '5,63,63,000',
  '-',
  '15,71,50,000',
  '4,55,02,000'],
 'GE': ['-',
  '59,92,000',
  '-38,00,000',
  '18,71,000',
  '-31,95,000',
  '9,66,04,000',
  '5,62,68,000',
  '-31,95,000',
  '3,55,52,000',
  '7,02,89,000'],
 'GS': [nan, '-', '1,45,03,000', '-', '-', nan, nan, '-', '9,59,32,000', nan],
 'HD': ['-',
  '25,19,000',
  '1,28,66,000',
  '1,88,39,000',
  '-24,63,000',
  '2,84,77,000',
  '2,31,66,000',
  '-24,63,000',
  '32,99,000',
  '3,58,22,000'],
 'IBM': ['-',
  '67,33,000',
  '53,70,000',
  '1,86,35,000',
  '-31,16,000',
  '3,91,65,000',
  '3,98,69,000',
  '-31,16,000',
  '2,05,97,000',
  '5,43,55,000'],
 'INTC': ['-',
  '1,20,91,000',
  '1,85,99,000',
  '3,47,74,000',
  '-1,55,73,000',
  '4,72,49,000',
  '2,47,54,000',
  '-1,55,73,000',
  '8,10,38,000',
  '3,38,97,000'],
 'JNJ': ['-',
  '73,78,000',
  '1,51,15,000',
  '2,42,52,000',
  '-33,99,000',
  '5,12,37,000',
  '4,24,93,000',
  '-33,99,000',
  '6,32,78,000',
  '3,26,35,000'],
 'JPM': [nan,
  '-',
  '3,88,30,000',
  '-',
  nan,
  nan,
  nan,
  nan,
  '27,93,54,000',
  nan],
 'MCD': ['-',
  '-',
  '51,60,800',
  '-',
  '-',
  '62,43,200',
  '61,81,200',
  '-',
  '-78,24,900',
  '3,51,96,800'],
 'MRK': ['-',
  '37,34,000',
  '70,27,000',
  '1,13,37,000',
  '-48,32,000',
  '2,77,64,000',
  '2,73,27,000',
  '-48,32,000',
  '2,53,17,000',
  '2,53,60,000'],
 'MSFT': ['-',
  '1,18,46,000',
  '5,60,15,000',
  '7,27,03,000',
  '-1,89,14,000',
  '18,19,15,000',
  '7,23,10,000',
  '-1,89,14,000',
  '11,83,04,000',
  '5,95,78,000'],
 'NKE': ['-',
  '7,99,000',
  '34,28,000',
  '46,44,000',
  '-8,10,000',
  '2,05,56,000',
  '82,84,000',
  '-8,10,000',
  '80,55,000',
  '94,06,000'],
 'PFE': ['-',
  '-',
  '1,10,92,000',
  '-',
  '-',
  '3,50,67,000',
  '2,59,20,000',
  '-',
  '6,32,38,000',
  '3,55,71,000'],
 'PG': ['-',
  '28,39,000',
  '1,39,33,000',
  '1,90,56,000',
  '-27,31,000',
  '2,79,87,000',
  '3,29,76,000',
  '-27,31,000',
  '4,65,21,000',
  '2,35,37,000'],
 'TRV': [nan,
  '8,21,000',
  '28,11,000',
  '70,81,000',
  nan,
  nan,
  nan,
  nan,
  '2,92,01,000',
  nan],
 'UNH': ['-',
  '29,26,000',
  '1,68,83,000',
  '2,52,36,000',
  '-21,50,000',
  '5,37,18,000',
  '7,24,20,000',
  '-21,50,000',
  '6,54,91,000',
  '3,86,48,000'],
 'VZ': ['-',
  '1,67,44,000',
  '1,88,90,000',
  '4,26,38,000',
  '-6,38,87,000',
  '5,45,94,000',
  '3,96,60,000',
  '-6,38,87,000',
  '6,78,42,000',
  '12,31,73,000'],
 'V': ['-',
  '7,91,000',
  '1,06,62,000',
  '1,19,40,000',
  '-6,47,000',
  '2,76,45,000',
  '1,45,10,000',
  '-6,47,000',
  '3,62,10,000',
  '2,10,71,000'],
 'WMT': ['-',
  '1,11,52,000',
  '1,35,10,000',
  '3,60,74,000',
  '-1,02,64,000',
  '9,00,67,000',
  '9,26,45,000',
  '-1,02,64,000',
  '8,09,25,000',
  '4,11,94,000']}