In [2]:
# Piotroski f score implementation (data scraped from yahoo finance)

import requests
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
tickers = ["AXP","AAPL","BA","CAT","CVX","CSCO","DIS","DOW", "XOM",
           "HD","IBM","INTC","JNJ","KO","MCD","MMM","MRK","MSFT",
           "NKE","PFE","PG","TRV","UTX","UNH","VZ","V","WMT","WBA"]

In [4]:
#list of tickers whose financial data needs to be extracted
financial_dir_cy = {} #directory to store current year's information
financial_dir_py = {} #directory to store last year's information
financial_dir_py2 = {} #directory to store last to last year's information

In [5]:
for ticker in tickers:
    try:
        print("scraping financial statement data for ",ticker)
        temp_dir = {}
        temp_dir2 = {}
        temp_dir3 = {}
    #getting balance sheet data from yahoo finance for the given ticker
        url = 'https://in.finance.yahoo.com/quote/'+ticker+'/balance-sheet?p='+ticker
        page = requests.get(url)
        page_content = page.content
        soup = BeautifulSoup(page_content,'html.parser')
        tabl = soup.find_all("div", {"class" : "M(0) Whs(n) BdEnd Bdc($seperatorColor) D(itb)"})
        for t in tabl:
            rows = t.find_all("div", {"class" : "rw-expnded"})
            for row in rows:
                temp_dir[row.get_text(separator='|').split("|")[0]]=row.get_text(separator='|').split("|")[1]
                temp_dir2[row.get_text(separator='|').split("|")[0]]=row.get_text(separator='|').split("|")[2]
                temp_dir3[row.get_text(separator='|').split("|")[0]]=row.get_text(separator='|').split("|")[3]
        
        #getting income statement data from yahoo finance for the given ticker
        url = 'https://in.finance.yahoo.com/quote/'+ticker+'/financials?p='+ticker
        page = requests.get(url)
        page_content = page.content
        soup = BeautifulSoup(page_content,'html.parser')
        tabl = soup.find_all("div", {"class" : "M(0) Whs(n) BdEnd Bdc($seperatorColor) D(itb)"})
        for t in tabl:
            rows = t.find_all("div", {"class" : "rw-expnded"})
            for row in rows:
                temp_dir[row.get_text(separator='|').split("|")[0]]=row.get_text(separator='|').split("|")[1]
                temp_dir2[row.get_text(separator='|').split("|")[0]]=row.get_text(separator='|').split("|")[2]
                temp_dir3[row.get_text(separator='|').split("|")[0]]=row.get_text(separator='|').split("|")[3]
        
        #getting cashflow statement data from yahoo finance for the given ticker
        url = 'https://in.finance.yahoo.com/quote/'+ticker+'/cash-flow?p='+ticker
        page = requests.get(url)
        page_content = page.content
        soup = BeautifulSoup(page_content,'html.parser')
        tabl = soup.find_all("div", {"class" : "M(0) Whs(n) BdEnd Bdc($seperatorColor) D(itb)"})
        for t in tabl:
            rows = t.find_all("div", {"class" : "rw-expnded"})
            for row in rows:
                temp_dir[row.get_text(separator='|').split("|")[0]]=row.get_text(separator='|').split("|")[1]
                temp_dir2[row.get_text(separator='|').split("|")[0]]=row.get_text(separator='|').split("|")[2]
                temp_dir3[row.get_text(separator='|').split("|")[0]]=row.get_text(separator='|').split("|")[3] 
        
        #combining all extracted information with the corresponding ticker
        financial_dir_cy[ticker] = temp_dir
        financial_dir_py[ticker] = temp_dir2
        financial_dir_py2[ticker] = temp_dir3
    except:
        print("Problem scraping data for ",ticker)

scraping financial statement data for  AXP
scraping financial statement data for  AAPL
scraping financial statement data for  BA
scraping financial statement data for  CAT
scraping financial statement data for  CVX
scraping financial statement data for  CSCO
scraping financial statement data for  DIS
scraping financial statement data for  DOW
scraping financial statement data for  XOM
scraping financial statement data for  HD
scraping financial statement data for  IBM
scraping financial statement data for  INTC
scraping financial statement data for  JNJ
scraping financial statement data for  KO
scraping financial statement data for  MCD
scraping financial statement data for  MMM
scraping financial statement data for  MRK
scraping financial statement data for  MSFT
scraping financial statement data for  NKE
scraping financial statement data for  PFE
scraping financial statement data for  PG
scraping financial statement data for  TRV
scraping financial statement data for  UTX
scraping financial statement data for  UNH
scraping financial statement data for  VZ
scraping financial statement data for  V
scraping financial statement data for  WMT
scraping financial statement data for  WBA

In [6]:
#storing information in pandas dataframe
combined_financials_cy = pd.DataFrame(financial_dir_cy)
#combined_financials_cy.dropna(axis=1,inplace=True) #dropping columns with NaN values
combined_financials_py = pd.DataFrame(financial_dir_py)
#combined_financials_py.dropna(axis=1,inplace=True)
combined_financials_py2 = pd.DataFrame(financial_dir_py2)
#combined_financials_py2.dropna(axis=1,inplace=True)
tickers = combined_financials_cy.columns #updating the tickers list based on only those tickers whose values were successfully extracted

In [7]:
# selecting relevant financial information for each stock using fundamental data
stats = ["Net income available to common shareholders",
         "Total assets",
         "Net cash provided by operating activities",
         "Long-term debt",
         "Other long-term liabilities",
         "Total current assets",
         "Total current liabilities",
         "Common stock",
         "Total revenue",
         "Gross profit"] # change as required

indx = ["NetIncome","TotAssets","CashFlowOps","LTDebt","OtherLTDebt",
        "CurrAssets","CurrLiab","CommStock","TotRevenue","GrossProfit"]

In [8]:
def info_filter(df,stats,indx):
    """function to filter relevant financial information for each 
       stock and transforming string inputs to numeric"""
    tickers = df.columns
    all_stats = {}
    for ticker in tickers:
        try:
            temp = df[ticker]
            ticker_stats = []
            for stat in stats:
                ticker_stats.append(temp.loc[stat])
            all_stats['{}'.format(ticker)] = ticker_stats
        except:
            print("can't read data for ",ticker)
    
    all_stats_df = pd.DataFrame(all_stats,index=indx)
    
    # cleansing of fundamental data imported in dataframe
    all_stats_df[tickers] = all_stats_df[tickers].replace({',': ''}, regex=True)
    for ticker in all_stats_df.columns:
        all_stats_df[ticker] = pd.to_numeric(all_stats_df[ticker].values,errors='coerce')
    return all_stats_df

In [9]:
def piotroski_f(df_cy,df_py,df_py2):
    """function to calculate f score of each stock and output information as dataframe"""
    f_score = {}
    tickers = df_cy.columns
    for ticker in tickers:
        ROA_FS = int(df_cy.loc["NetIncome",ticker]/((df_cy.loc["TotAssets",ticker]+df_py.loc["TotAssets",ticker])/2) > 0)
        CFO_FS = int(df_cy.loc["CashFlowOps",ticker] > 0)
        ROA_D_FS = int(df_cy.loc["NetIncome",ticker]/(df_cy.loc["TotAssets",ticker]+df_py.loc["TotAssets",ticker])/2 > df_py.loc["NetIncome",ticker]/(df_py.loc["TotAssets",ticker]+df_py2.loc["TotAssets",ticker])/2)
        CFO_ROA_FS = int(df_cy.loc["CashFlowOps",ticker]/df_cy.loc["TotAssets",ticker] > df_cy.loc["NetIncome",ticker]/((df_cy.loc["TotAssets",ticker]+df_py.loc["TotAssets",ticker])/2))
        LTD_FS = int((df_cy.loc["LTDebt",ticker] + df_cy.loc["OtherLTDebt",ticker])<(df_py.loc["LTDebt",ticker] + df_py.loc["OtherLTDebt",ticker]))
        CR_FS = int((df_cy.loc["CurrAssets",ticker]/df_cy.loc["CurrLiab",ticker])>(df_py.loc["CurrAssets",ticker]/df_py.loc["CurrLiab",ticker]))
        DILUTION_FS = int(df_cy.loc["CommStock",ticker] <= df_py.loc["CommStock",ticker])
        GM_FS = int((df_cy.loc["GrossProfit",ticker]/df_cy.loc["TotRevenue",ticker])>(df_py.loc["GrossProfit",ticker]/df_py.loc["TotRevenue",ticker]))
        ATO_FS = int(df_cy.loc["TotRevenue",ticker]/((df_cy.loc["TotAssets",ticker]+df_py.loc["TotAssets",ticker])/2)>df_py.loc["TotRevenue",ticker]/((df_py.loc["TotAssets",ticker]+df_py2.loc["TotAssets",ticker])/2))
        f_score[ticker] = [ROA_FS,CFO_FS,ROA_D_FS,CFO_ROA_FS,LTD_FS,CR_FS,DILUTION_FS,GM_FS,ATO_FS]
    f_score_df = pd.DataFrame(f_score,index=["PosROA","PosCFO","ROAChange","Accruals","Leverage","Liquidity","Dilution","GM","ATO"])
    return f_score_df

In [12]:
# Selecting stocks with highest Piotroski f score
transformed_df_cy = info_filter(combined_financials_cy,stats,indx)
transformed_df_py = info_filter(combined_financials_py,stats,indx)
transformed_df_py2 = info_filter(combined_financials_py2,stats,indx)

transformed_df_cy

,AXP,AAPL,BA,CAT,CVX,CSCO,DIS,DOW,XOM,HD,...,NKE,PFE,PG,TRV,UTX,UNH,VZ,V,WMT,WBA
NetIncome,4909000.0,76311000,-11782000,3436000,-7765000.0,10129000,-4954000,1977000,-19100000.0,12866000,...,3428000.0,11092000.0,13933000,2811000.0,NaN,16883000,18890000,10662000,13510000.0,-617000
TotAssets,191367000.0,323888000,152136000,78324000,239790000.0,94853000,201549000,61470000,332750000.0,70581000,...,31342000.0,154229000.0,120700000,116764000.0,NaN,197289000,316481000,80919000,252496000.0,87174000
CashFlowOps,10090000.0,99591000,-17495000,7125000,10055000.0,15109000,6091000,4696000,NaN,18839000,...,4644000.0,NaN,19056000,7081000.0,NaN,25236000,42638000,11940000,36074000.0,5556000
LTDebt,NaN,98667000,61752000,25896000,42320000.0,11578000,52917000,16491000,45502000.0,35822000,...,9406000.0,35571000.0,23537000,NaN,NaN,38648000,123173000,21071000,41194000.0,12203000
OtherLTDebt,NaN,26320000,1486000,4358000,NaN,2147000,10753000,7292000,21242000.0,1807000,...,NaN,6669000.0,1149000,NaN,NaN,12315000,12008000,3891000,NaN,3294000
CurrAssets,NaN,143713000,121642000,39464000,26078000.0,43573000,35251000,19084000,44893000.0,28477000,...,20556000.0,35067000.0,27987000,NaN,NaN,53718000,54594000,27645000,90067000.0,18073000
CurrLiab,NaN,105392000,87280000,25717000,22183000.0,25331000,26628000,11108000,56363000.0,23166000,...,8284000.0,25920000.0,32976000,NaN,NaN,72420000,39660000,14510000,92645000.0,27070000
CommStock,161000.0,50779000,5061000,6230000,1832000.0,41202000,54497000,8000,15688000.0,89000,...,3000.0,470000.0,4906000,23743000.0,NaN,10000,429000,5086000,282000.0,12000
TotRevenue,34112000.0,325406000,56467000,43000000,95842000.0,48026000,60760000,40654000,182587000.0,132110000,...,38507000.0,44462000.0,74870000,32386000.0,NaN,261327000,129549000,21354000,559151000.0,142507000
GrossProfit,NaN,129776000,-4416000,12633000,23789000.0,30820000,18139000,5476000,NaN,44853000,...,16660000.0,33937000.0,38611000,NaN,NaN,67397000,77122000,16681000,138836000.0,27634000

In [13]:
f_score_df = piotroski_f(transformed_df_cy,transformed_df_py,transformed_df_py2)
f_score_df

,AXP,AAPL,BA,CAT,CVX,CSCO,DIS,DOW,XOM,HD,...,NKE,PFE,PG,TRV,UTX,UNH,VZ,V,WMT,WBA
PosROA,1,1,0,1,0,1,0,1,0,1,...,1,1,1,1,0,1,1,1,1,0
PosCFO,1,1,0,1,1,1,1,1,0,1,...,1,0,1,1,0,1,1,1,1,1
ROAChange,1,1,1,1,0,0,0,1,1,0,...,1,1,1,0,0,0,0,0,0,0
Accruals,1,1,0,1,1,1,1,1,0,1,...,1,0,1,1,0,1,1,1,1,1
Leverage,0,0,0,1,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
Liquidity,0,0,1,1,1,1,1,1,1,1,...,1,1,1,0,0,1,1,1,1,0
Dilution,1,0,1,0,1,0,0,1,0,1,...,1,1,1,0,0,0,1,1,1,1
GM,0,1,1,1,0,0,0,0,0,0,...,0,0,1,0,0,1,0,0,0,0
ATO,0,1,0,1,1,1,0,1,1,0,...,0,1,1,0,0,0,0,0,0,0

In [14]:
f_score_df.sum().sort_values(ascending=False)

CAT     8
PG      8
DOW     7
MSFT    7
KO      6
AAPL    6
CSCO    6
PFE     6
NKE     6
WMT     5
CVX     5
HD      5
JNJ     5
AXP     5
MMM     5
UNH     5
VZ      5
V       5
MCD     4
INTC    4
IBM     4
MRK     4
BA      4
WBA     4
XOM     3
TRV     3
DIS     3
UTX     0
dtype: int64